<!--noptimize-->
<script async type="text/javascript">
function lazyAdsByGoogle() {
var element = document.createElement("script");
element.src = "https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js";
document.body.appendChild(element);
}
if (window.addEventListener)
window.addEventListener("load", lazyAdsByGoogle, false);
else if (window.attachEvent)
window.attachEvent("onload", lazyAdsByGoogle);
else window.onload = lazyAdsByGoogle;
</script>
<!--/noptimize-->
<!-- TheNinja Core3 --> 
<ins class="adsbygoogle" data-ad-client="ca-pub-8967932238961461" data-ad-slot="6448563069"></ins> 
<script async> (adsbygoogle = window.adsbygoogle || []).push({}); </script>